### PR TITLE
test: test nvme entities over HTTP

### PR DESCRIPTION
**Pull request by artek-koltun**

### CODE REVIEW

**Review by glimchb — COMMENTED** [review]
please mention an example for HTTP in the readme page as well

**Review by glimchb — APPROVED** [review]
lgtm once CI failure 500 is fixed

**Comment by artek-koltun** [comment]
> lgtm once CI failure 500 is fixed
> 
> ```
> curl: (22) The requested URL returned error: 500
> ```
> 
> from https://github.com/opiproject/opi-spdk-bridge/actions/runs/7740869173/job/21106738684?pr=878

This is fixed in those PRs
https://github.com/opiproject/opi-spdk-bridge/pull/880
https://github.com/opiproject/godpu/pull/438
please take a look

**Comment by artek-koltun** [comment]
Merging as is. Let's discuss how to organize http tests in Slack

**Pull request merged**
