### PR TITLE
Replace deepcopier with ProtoClone

### LINKED ISSUE #393: do not use deepcopier to create a deep copy of gRPC structs
Looks like deepcopier is not able to create a deep copy of a nested pointer grpc type
```
func TestDeepcopier(t *testing.T) {
	t.Run("test ptr in deepcopier", func(t *testing.T) {
		f1 := &pb.EncryptedVolume{VolumeId: &pc.ObjectKey{Value: "abc"}}
		f2 := &pb.EncryptedVolume{}
		deepcopier.Copy(f1).To(f2)
		log.Println(f1)
		log.Println(f2)
		log.Printf("%p %p", f1.VolumeId, f2.VolumeId)
		if !proto.Equal(f1, f2) {
			t.Errorf("Expect deep copy of structure %v, got %v", f1, f2)
		}
		if f1.VolumeId == f2.VolumeId {
			t.Errorf("f1 vol ptr cannot be equal to f2 vol ptr")
		}
	})
}
```
shows
```
2023/05/29 11:54:05 volume_id:{value:"abc"}
2023/05/29 11:54:05 volume_id:{value:"abc"}
2023/05/29 11:54:05 0xc0000c9c00 0xc0000c9c00
--- FAIL: TestDeepcopier (0.00s)
    --- FAIL: TestDeepcopier/test_ptr_in_deepcopier (0.00s)
        /home/abc/test/test_test.go:518: f1 vol ptr cannot be equal to f2 vol ptr
FAIL
```

For gRPC structures, [proto.Clone](https://pkg.go.dev/github.com/golang/protobuf/proto#Clone) should be used instead

### PR DESCRIPTION
**Pull request by artek-koltun**
Fixes #393

### CODE REVIEW

**Review by glimchb — COMMENTED** [review]
what is the benefit of wrapping `proto.Clone` into `ProtoClone` function ?

**Comment by artek-koltun** [comment]
> what is the benefit of wrapping `proto.Clone` into `ProtoClone` function ?

With `ProtoClone` we don't need to type assert (cast to a specific type) every time we create a copy. We already know the type we need. Type asserting all the time I found irritating and decided to provide a generic wrapper.
Without `ProtoClone`
```
var a *pb.NvmeController
var b *pb.NvmeSubsystem
var c *pb.VirtioBlk
// ...
copyA := proto.Clone(a).(*pb.NvmeController)
copyB := proto.Clone(b).(*pb.NvmeSubsystem)
copyC := proto.Clone(c).(*pb.VirtioBlk)
```
with `ProtoClone`
```
var a *pb.NvmeController
var b *pb.NvmeSubsystem
var c *pb.VirtioBlk
// ...
copyA := ProtoClone(a)
copyB := ProtoClone(b)
copyC := ProtoClone(c)
```

**Comment by glimchb** [comment]
> Also, it is harder to make a mistake and cast to a wrong type

appreciate the reasoning!

**Review by glimchb — APPROVED** [review]
approved

**Pull request merged**
