### PR TITLE
keep opi-api version in built image's label

### PR DESCRIPTION
**Pull request by yanjing1104**
Solution for https://github.com/opiproject/opi-spdk-bridge/issues/576

Example usage:
```bash
# docker build . --build-arg="OPI_API_VERSION=test" -t opiproject/opi-spdk-bridge

# docker inspect 45fe98b6d6dd --format '{{ json .Config.Labels }}' | sed 's/,/\n/g'
{"opi_api_version":"test"}

# docker build . --label "opi_api_version=test1" -t opiproject/opi-spdk-bridge

# docker inspect 1304b6107289 --format '{{ json .Config.Labels }}' | sed 's/,/\n/g'
{"opi_api_version":"test1"}
```

### CODE REVIEW

**Comment by artek-koltun** [comment]
Hi Jing! Could you please also update [github action](https://github.com/opiproject/opi-spdk-bridge/blob/main/.github/workflows/docker-publish.yml), so API version is incorporated into the built images?

**Review by artek-koltun — CHANGES_REQUESTED** [review]
Need to validate it before approving

**Comment by yanjing1104** [comment]
Validating the Label locally, will re-open this PR once it works as expected.

**Comment by artek-koltun** [comment]
You can also try to use `OPI_API_VERSION` variable with `labels` to get version incorporated
```yml
- name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }},
            opi-api-version=${{ env.OPI_API_VERSION }}

**Comment by yanjing1104** [comment]
Hey sry for the inconvenience. This pr could not be re-opened as I deleted the forked repository when I was trying to solve the issue of pushing the docker image to my own gh container registry, #602 is opened to replace this one. The code changes and the LABEL test result of the corresponding docker image are updated in #602 too.

**Pull request closed without merging**
