### PR TITLE
Use sorting for list calls

### PR DESCRIPTION
**Pull request by artek-koltun**

### CODE REVIEW

**Review by glimchb — CHANGES_REQUESTED** [review]
great! thanks.
can we be consistent and add sorting to all `List*` functions then ?

**Comment by artek-koltun** [comment]
> great! thanks. can we be consistent and add sorting to all `List*` functions then ?

Planned to do that in the following PRs

**Comment by artek-koltun** [comment]
Ok, reworked

**Review by glimchb — APPROVED** [review]
great work, thanks for fixing for all APIs

**Pull request merged**
